### ISSUE TITLE
cant find bitbucket.org/cleanflo/zoho

### ISSUE THREAD

**Issue by beatscode** [schmorrison/Zoho#1]
Thanks for starting this project. I tried running a test and couldn't get passed the following error. Can't find cleanflo/zoho.
```
package com.drleonardo/zoho (test)
	imports github.com/schmorrison/Zoho/crm
	imports bitbucket.org/cleanflo/zoho: cannot find package "bitbucket.org/cleanflo/zoho" in any of:
	/usr/local/opt/go/libexec/src/bitbucket.org/cleanflo/zoho (from $GOROOT)
	/Users/alex/projects/go/src/bitbucket.org/cleanflo/zoho (from $GOPATH)
FAIL	com.drleonardo/zoho [setup failed]
Process exiting with code: 1
```
Any pointers?

**Comment by schmorrison** [comment]
I seem to have references to the private repo in one of the packages.

I'll take some time tonight to write some good instructions, and make notes of functions that are not working yet.

I'll fix that repo issue right away.
