### ISSUE TITLE
rand not used properly

### ISSUE THREAD

**Issue by vazha** [schmorrison/Zoho#16]
rand not used properly in crm.go
id = append(id, keyspace[rand.Intn(len(keyspace))])  always produced the same sequence.

Can be used as follow:
			s := rand.NewSource(time.Now().UnixNano())
			r := rand.New(s)
			id = append(id, keyspace[r.Intn(len(keyspace))])

**Comment by schmorrison** [comment]
Ok thanks. Wanna make a PR?

Best regards,

schmorrison

**Comment by schmorrison** [comment]
Closed by #17
