### ISSUE TITLE
License

### ISSUE THREAD

**Issue by kardianos** [schmorrison/Zoho#20]
This looks like a nice start for integration to Zoho.

Please be aware, it is doubtful many people will be able to use a GPL3 licensed package. It is likely almost everyone who is interested in using both Go and Zoho will be unable to use this package.

**Comment by schmorrison** [comment]
Thanks for your comment, and duly noted. What are your suggestions for license? Are there any considerations I should make when changing the lisense; like versioning the current license to a different branch?

**Comment by kardianos** [comment]
You could put in a different branch, but just changing the license and
tagging a new release would be enough.

BSD and MIT are both popular choices. The problem with GPL is it is viral
and Go is statically linked.

**Comment by schmorrison** [comment]
Very good. Thanks for you suggestion. I am by no means attached to the
current license and will push the updated lisence in a bit.

PRs or feature requests are appreciated.

I am working on a new branch which is attempting to generate the structs
for each modules data type. Maybe I'll push the progress at the same time.

**Comment by kardianos** [comment]
Thanks!
