### ISSUE TITLE
InvoiceAPIEndpoint does not respect SetZohoTLD(s string)

### ISSUE THREAD

**Issue by Jammizzle** [schmorrison/Zoho#30]
With InvoiceApiEndpoint being a const, any use outside of .com will not succeed

**Comment by schmorrison** [comment]
Ok thank you. I think I can issue a simple fix.

**Comment by Jammizzle** [comment]
Possibly moving the InvoiceAPIEndpoint const into a 

```go
var (
	InvoiceAPIEndpoint string = "https://invoice.zoho.com/api/v3/"
)

// SetZohoTLD can be used to set the TLD extension for API calls for example for Zoho in EU and China.
// by default this is set to "com", other options are "eu" and "ch"
func (z *API) SetZohoTLD(s string) {
	InvoiceAPIEndpoint = fmt.Sprintf("https://invoice.zoho.%s/api/v3/", s)
}

```

To match the main package?

**Comment by Jammizzle** [comment]
Can then optionally add the 

```go
InvoiceAPIEndpoint = fmt.Sprintf("https://invoice.zoho.%s/api/v3/", z.ZohoTLD)
```

Into the `New` function in invoice.go:38

**Comment by schmorrison** [comment]
Ok, that woulda worked.

I just did a search and replace regex across that folder. I pushed the change to [issue-30](https://github.com/schmorrison/Zoho/tree/issue-30), just wanted to merge the last PR before I pulled this in. I think I can place a few updates under a tag single revision.
