### ISSUE TITLE
can i work for you without payment. i need learning more about golang. if can, contact to me skype:congbv.hut86

### ISSUE THREAD

**Issue by congbv** [schmorrison/Zoho#6]

**Comment by schmorrison** [comment]
Please work on this project all you like, if you have any contributions I will audit your code or suggest good starting points. I haven’t abandoned it, but I haven’t worked on it since October.

Sorry I don’t use Skype. Email is best to reach me.

**Comment by congbv** [comment]
due to I don't have much experiences with develop software especially golang,  but i desire learning golang , i can't work by myself, i were needed your instructions, break down big problem into small problems, i have 6 years experiences about sysadmin, intergrate system and databases ( oracle, mysql, postgresql) . i can good well with shellscript. basic level with python, golang. i want to be one backend developer or DevOps.
would you please give me once chance to get it.
Finally, I would like to thank you
P/s: my email: congbvit3k50@gmail.com.
